@startchen

entity "Estudiante" as student {
  estudiante_id <<key>>
  nombre
  edad
  email <<multi>>
}

entity "Curso" as curse {
  curso_id <<key>>
  nombre
  creditos
}

entity “Inscripción” as inscription <<weak>>{
  inscripción_id <<key>>
  fecha_inscripción
}

entity "Profesor" as teacher {
  profesor_id <<key>>
  nombre
  email <<multi>>
}

relationship realizar {
}

relationship inscribir {
}

relationship impartir {
}

student -(1,N)- realizar
realizar -(M,1)- inscription
inscription -(1,N)- inscribir
inscribir -(M,1)- curse
curse -(1,N)- impartir
impartir -(M,1)- teacher
@endchen